services:
  book-service:
    build: modsen-book-service
    image: modsen-book-service
    container_name: book-service
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      DB_URL: jdbc:postgresql://db-book-service:5432/book-service-db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      CONFIG_SERVER_URL: http://config-server:8071
    ports:
      - 8080:8080
    networks:
      - lib_app_network
    depends_on:
      db-book-service:
        condition: service_healthy
      config-server:
        condition: service_healthy

  db-book-service:
    image: postgres:15-alpine
    container_name: db-book-service
    restart: always
    healthcheck:
      test: pg_isready -U postgres -d book-service-db
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: book-service-db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lib_app_network

  config-server:
    build: modsen-config-server
    image: modsen-config-server
    container_name: config-server
    restart: always
    healthcheck:
      test: wget -qO- http://localhost:8071/actuator/health
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8071:8071
    networks:
      - lib_app_network

volumes:
  pgdata:

networks:
  lib_app_network:
